services:
  - type: worker
    name: telegraph-bot
    env: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
